### ISSUE TITLE
Update headline text styles

### ISSUE THREAD

**Issue by brandonhaslegs** [velocitylabs-org/turtle#71]
The huge font on the homepage is too big. These values work better:

`font-size: 8.75vw;`
`margin: 0 4vw;`

**Comment by Victor-Salomon** [comment]
@brandonhaslegs can you please confirm we talk about this one : 

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/1e687b87-5f67-41f9-813f-656007e1dc76">

**Comment by brandonhaslegs** [comment]
yes that's right.

**Comment by brandonhaslegs** [comment]
Right now it looks like this sometimes
<img width="936" alt="image" src="https://github.com/user-attachments/assets/fba45bff-4d73-4313-97b0-3b9d1e2361e5">
so the font size based on vw is ideal because it constantly scales with the browser width.

and the margin is necessary to prevent the text from hitting the sides
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/859d5194-2e78-425b-90c1-7899993cd509">

**Comment by Victor-Salomon** [comment]
Thanks for the feedback. 
@brandonhaslegs, 

We will implement it asap
