### ISSUE TITLE
Add correct letter spacing to fonts

### ISSUE THREAD

**Issue by brandonhaslegs** [velocitylabs-org/turtle#95]
Add 0.03em letter-spacing to Large Medium and Small text styles.

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/36b8a8b2-bcbb-4a39-a4f7-7f2444b12924">

**Comment by brandonhaslegs** [comment]
Also make sure the letter spacing is right for the larger text styles. I think it is. Just noticed the smaller text styles are missing the letter spacing.

**Comment by NunoAlexandre** [comment]
> Also make sure the letter spacing is right for the larger text styles. I think it is. Just noticed the smaller text styles are missing the letter spacing.

yeah I actually noticed this yesterday as well 👍  on our list
